### ISSUE TITLE
Allow names to be attached to modifiers

### ISSUE THREAD

**Issue by danieldelcore** [danieldelcore/trousers#30]
Feedback from @thekashey

![image](https://user-images.githubusercontent.com/3030010/63391187-f9afdf00-c3f4-11e9-89df-62389536e234.png)

Allow users to supply a name to modifiers to make them debugger friendly. 

```javascript
const styles = styleCollector('button')
  .element``
  .modifier('primary', props => props.primary)`
    color: red;
  `;
```

the resulting className would end up looking something like `button__40241422510--primary-123131`

🤔Perhaps we could omit the hash if a name is provided

**Comment by theKashey** [comment]
Let's dont break the API :)
```js
const styles = styleCollector('button')
  .element``
  .modifier(props => props.primary, 'primary')`
    color: red;
  `;
```

**Comment by danieldelcore** [comment]
https://github.com/danieldelcore/trousers/pull/32

😄

**Comment by danieldelcore** [comment]
@theKashey 

Done! https://github.com/danieldelcore/trousers/releases/tag/v2.1.0
Thanks for the AWESOME suggestion ❤️

**Comment by theKashey** [comment]
Formating is a bit borked at release note :)
